routes/web.php
        Route::get('/exportar/descarga', 'CertificationController@downloadExcel')->name('certifications.export_download_excel');
        Route::get('/exportar/descarga-desaprobados', 'CertificationController@downloadExcelRecovery')->name('certifications.export_download_excel_recovery');

        Route::get('/encuestas/exportar', 'SurveyController@exportData')->name('surveys.export_data');
        Route::get('/encuestas/exportar-perfil', 'SurveyController@exportDataProfile')->name('surveys.export_data_profile');
        Route::get('/encuestas/exportar/descarga', 'SurveyController@downloadExcel')->name('surveys.export_download_excel');
        Route::get('/encuestas/descarga-perfil', 'SurveyController@downloadExcelprofile')->name('surveys.export_download_excel_profile');

        Route::get('/archivos', 'FileController@managementFile')->name('files.management');
        Route::get('/archivos/{file}/descarga', 'FileController@downloadFile')->name('files.download');
        Route::post('/archivos', 'FileController@storeFile')->name('files.store');
        Route::delete('/archivos/{file}', 'FileController@destroy')->name('files.destroy');
        
        Route::get('/archivos-hist', 'FileController@managementHistFile')->name('files.managementhist');
        Route::get('/archivos-hist', 'FileController@filterFile')->name('files.filter');
        Route::get('/archivos-hist/{file}/descarga', 'FileController@downloadFile')->name('files.download');
        Route::post('/archivos-hist', 'FileController@storeFile')->name('files.store');
        Route::delete('/archivos-hist/{file}', 'FileController@destroy')->name('files.destroy');

        Route::get('/asistencia/grupal', 'CertificationController@groupAssist')->name('certifications.group_assist');
        Route::get('/asistencia/individual', 'CertificationController@individualAssist')->name('certifications.individual_assist');
        Route::get('/asistencia/grupal/{event}', 'CertificationController@exportGroupAssistPDF')->name('certifications.group_assist_pdf');
        Route::get('/asistencia/grupal-atacocha/{event}', 'CertificationController@exportGroupAssistAtacochaPDF')->name('certifications.group_assist_atacocha_pdf');
        Route::get('/asistencia/grupal-porvenir/{event}', 'CertificationController@exportGroupAssistPorvenirPDF')->name('certifications.group_assist_porvenir_pdf');
        Route::get('/asistencia/individual/{certification}', 'CertificationController@exportIndividualAssistPDF')->name('certifications.individual_assist_pdf');

        Route::get('/certificados-antiguos', 'CertificationOldController@index')->name('certification_old.index');
        Route::get('/certificados-antiguos/descarga', 'CertificationOldController@download')->name('certification_old.download');

        Route::get('/doc-certificados/anexos', 'CertifiedDocumentsController@anexos')->name('certified_documents.anexos');
        Route::get('/doc-certificados/asistencias', 'CertifiedDocumentsController@assists')->name('certified_documents.assists');

        Route::get('/usuarios/import/template', 'UserController@downloadTemplate')->name('users.import.download_template');

        Route::resource('/unidades-mineras', 'MiningUnitController', ['names' => 'mining_units', 'parameters' => ['unidades-mineras' => 'mining_unit'], 'except' => ['show']]);
        Route::resource('/companias', 'CompanyController', ['names' => 'companies', 'parameters' => ['companias' => 'company']]);
        Route::resource('/owner-companies', 'OwnerCompanyController', ['names' => 'owner_companies', 'parameters' => ['owner-companies' => 'owner_company'], 'except' => ['show']]);
        Route::resource('/salas', 'RoomController', ['names' => 'rooms', 'parameters' => ['salas' => 'room']]);
        Route::resource('/cursos', 'CourseController', ['names' => 'courses', 'parameters' => ['cursos' => 'course']]);
        #Route::post('/contenidos/{content}', 'ELearningContentController@update')->name('elearnings.contents.update');
        Route::resource('/e-learnings', 'ELearningController', ['names' => 'elearnings', 'parameters' => ['e-learnings' => 'elearning']]);
        Route::resource('e-learnings.contenidos', 'ELearningContentController', ['names' => 'elearnings.contents', 'parameters' => ['e-learnings' => 'elearning','contenidos' => 'content'], 'except' => ['index']])->shallow();
        Route::resource('/usuarios', 'UserController', ['names' => 'users', 'parameters' => ['usuarios' => 'user']]);
        Route::resource('/examenes', 'ExamController', ['names' => 'exams', 'parameters' => ['examenes' => 'exam']]);
        Route::resource('examenes.preguntas', 'ExamQuestionController', ['names' => 'exams.questions', 'parameters' => ['examenes' => 'exam','preguntas' => 'question'], 'except' => ['index']])->shallow();

        Route::post('/alternativas-dinamicas/{dynamic_alternative}', 'DynamicQuestionAlternativeController@selectCorrectAlternative')->name('dynamic_questions.dynamic_alternatives.select_correct');
        Route::post('/preguntas-dinamicas/{dynamic_question}', 'DynamicExamQuestionController@storeMultimedia')->name('dynamic_exams.dynamic_questions.store_file');
        Route::resource('/examenes-dinamicos', 'DynamicExamController', ['names' => 'dynamic_exams', 'parameters' => ['examenes-dinamicos' => 'dynamic_exam']]);
        Route::resource('/examenes-prueba-dinamicos', 'DynamicTestExamController', ['names' => 'dynamic_test_exams', 'parameters' => ['examenes-prueba-dinamicos' => 'dynamic_test_exam']]);
        Route::resource('examenes-dinamicos.preguntas-dinamicas', 'DynamicExamQuestionController', ['names' => 'dynamic_exams.dynamic_questions', 'parameters' => ['examenes-dinamicos' => 'dynamic_exam','preguntas-dinamicas' => 'dynamic_question'], 'except' => ['index']])->shallow();
        Route::resource('preguntas-dinamicas.alternativas-dinamicas', 'DynamicQuestionAlternativeController', ['names' => 'dynamic_questions.dynamic_alternatives', 'parameters' => ['preguntas-dinamicas' => 'dynamic_question','alternativas-dinamicas' => 'dynamic_alternative'], 'except' => ['index']])->shallow();


        Route::resource('/eventos', 'EventController', ['names' => 'events', 'parameters' => ['eventos' => 'event']]);
        Route::resource('/certificados', 'CertificationController', ['names' => 'certifications', 'parameters' => ['certificados' => 'certification']]);
        Route::resource('/encuestas', 'SurveyController', ['names' => 'surveys', 'parameters' => ['encuestas' => 'survey']]);
        Route::resource('encuestas.grupos', 'GroupController', ['names' => 'groups', 'parameters' => ['encuestas' => 'survey','grupos' => 'group'], 'except' => ['index']])->shallow();
        Route::resource('grupos.enunciados', 'StatementController', ['names' => 'statements', 'parameters' => ['grupos' => 'group','enunciados' => 'statement'], 'except' => ['index']])->shallow();
        Route::resource('enunciados.opciones', 'OptionController', ['names' => 'options', 'parameters' => ['enunciados' => 'statement','opciones' => 'option'], 'except' => ['index','show']])->shallow();

    });

    Route::prefix('aula')->namespace('Classroom')->middleware('only.classroom')->group(function(){
        Route::get('/','ClassroomController@home')->name('classroom.home');
        Route::get('/perfil_encuesta','ClassroomController@profile_survey')->name('classroom.profile_survey');
        Route::get('/perfil','ProfileController@index')->name('classroom.profile.index');
        Route::post('perfil-usuario','ProfileController@userProfile')->name('classroom.profile.user_profile');

        Route::get('/e-learnings/contenidos/archivos/{file}/descarga', 'ELearningController@downloadFile')->name('classroom.elearnings.contents.files.download');
        Route::get('/e-learnings','ELearningController@index')->name('classroom.elearnings.index');
        Route::get('/e-learnings/cazador','ELearningController@cazador')->name('classroom.elearnings.cazador');
        Route::get('/e-learnings/cazador-prot-maquinas','ELearningController@cazadorProtMaquinas')->name('classroom.elearnings.cazador_prot_maquinas');
        Route::get('/e-learnings/cazador-prev-caidas','ELearningController@cazadorPrevCaidas')->name('classroom.elearnings.cazador_prev_caidas');

        Route::get('/cursos','CourseController@index')->name('classroom.courses.index')->middleware('not.instructor');
        Route::get('/cursos/vivo/list','CourseController@liveList')->name('classroom.courses.live_list')->middleware('not.instructor');
        Route::get('/cursos/vivo/list-security','CourseController@liveSecurityList')->name('classroom.courses.live_security_list')->middleware('not.instructor');
        Route::get('/cursos/vivo/{certification}','CourseController@live')->name('classroom.courses.live')->middleware('not.instructor');
        Route::get('/cursos/recuperacion','CourseController@retrieval')->name('classroom.courses.retrieval')->middleware('not.instructor');

        Route::get('/firma-digital','DigitalSignatureController@index')->name('classroom.digital_signatures.index');
        Route::get('/firma-digital/crear','DigitalSignatureController@create')->name('classroom.digital_signatures.create');
        Route::post('/firma-digital/crear','DigitalSignatureController@store')->name('classroom.digital_signatures.store');
        
        Route::get('/firma-digital-security/{event}','DigitalSignatureController@indexSecurity')->name('classroom.digital_signatures.index_security');
        Route::get('/firma-digital-security/crear-security/{event}','DigitalSignatureController@createSecurity')->name('classroom.digital_signatures.create_security');
        Route::post('/firma-digital-security/crear-security/{event}','DigitalSignatureController@storeSecurity')->name('classroom.digital_signatures.store_security');
        
        Route::get('/firma-digital-security_por/{event}','DigitalSignatureController@indexSecurityPor')->name('classroom.digital_signatures.index_security_por');

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Facades\Gate;


class Company extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'description',
        'abbreviation',
        'ruc',
        'address',
        'telephone',
        'name_ref',
        'telephone_ref',
        'email_ref',
        'active',
    ];

    /**
     * Relationships
     */
    public function users()
    {
        return $this->hasMany('App\Models\User', 'company_id');
    }

    public function certifications()
    {
        return $this->hasMany('App\Models\Certification', 'company_id');
    }

    static function getDatatable()
    {
        $query = Company::with(['users']);

        $allCompanies = DataTables::of($query)
            ->addColumn('description', function ($company) {
                return $company->description ?? '-';
            })
            ->editColumn('ruc', function ($company) {
                return $company->ruc ?? '-';
            })
            ->editColumn('action', function ($company) {
                $btn = "";

                $btn .= '<a href="' . route('companies.edit', $company) . '" class="rgba-white-sligh"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>';

                if (Gate::allows('canDelete', $company)) {

                    $modal = view('components.deleteModal', [
                        'url_delete' => route('companies.destroy', $company->id),
                        'object' => 'Usuario',
                        'id' => $company->id,
                        'description' => $company->description
                    ])->render();

                    $btn .= '<a class="btn waves-effect" data-toggle="modal" data-target="#eliminacion-registro-' . $company->id . '"
                                    href="javascript:;">
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </a>' . $modal;
                }

                return $btn;
            })
            ->rawColumns(['action'])
            ->make(true);

        return $allCompanies;
    }
}

app/Http/Controllers/Admin/CompanyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Company;
use App\Http\Requests\Company\CompanyStoreRequest;
use App\Http\Requests\Company\CompanyUpdateRequest;
use App\Http\Entities\CompanyEntity;
use Illuminate\Http\Request;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if ($request->ajax()) {
            return Company::getDatatable();
        }
        // $companies = CompanyEntity::allWithRelationships();
        return view('admin.companies.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $company = new Company();
        return view('admin.companies.create',compact('company'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyStoreRequest $request)
    {
        $company = CompanyEntity::store($request);

        if($company){
            return redirect()->route('companies.show',$company->id)->with(['status' => 'success','action' => 'created','message' => 'Se registró correctamente.']);
        }
        return redirect()->route('companies.index')->withErrors(['message'=>'No se registró.']);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        return view('admin.companies.show',compact('company'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('admin.companies.edit',compact('company'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(CompanyUpdateRequest $request, Company $company)
    {
        CompanyEntity::update($request,$company);

        return redirect()->route('companies.show',$company->id)
        ->with(['status' => 'success','action' => 'updated','message' => 'Se actualizó correctamente.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        $this->authorize('canDelete', $company);

        $result =  CompanyEntity::destroy($company);
        return redirect()->route('companies.index')
        ->with(['status' => 'success','action' => 'deleted','message' => 'Se eliminó el registro correctamente.']);
    }
}

resources/views/admin/companies/create.blade.php
@extends('adminlte::page')

@section('title', 'Empresa')

@section('content_header')
    <h1>CREAR EMPRESA</h1>
@stop

@section('content')
    <div class="card">
        <form action="{{ route('companies.store') }}" method="post">
            @csrf
            @include('admin.companies.partials.form')
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Agregar</button>
            </div>
        </form>
    </div>
@stop

resources/views/admin/companies/edit.blade.php
@extends('adminlte::page')

@section('title', 'Empresa')

@section('content_header')
    <h1>EDITAR EMPRESA</h1>
@stop

@section('content')
    <div class="card">
        <form action="{{ route('companies.update',$company->id) }}" method="post">
            @csrf
            @method('PUT')
            @include('admin.companies.partials.form')
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Actualizar</button>
            </div>
        </form>
    </div>
@stop

resources/views/admin/companies/index.blade.php
@extends('adminlte::page')

@section('title', 'Empresa')

@section('plugins.Datatables', true)

@section('content_header')
    @include('components.alerts', ['object' => 'Empresa'])
    <h1 class="card-title">EMPRESAS</h1> <a href="{{ route('companies.create') }}" class="btn btn-primary"
        style="margin-left:10px;"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>Crear</a>
@stop

@section('content')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Lista de Empresas</h3>

        </div>
        <div class="card-body">
            <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table id="table_index_company" class="table table-bordered table-striped dataTable" role="grid"
                            aria-describedby="example1_info" data-url="{{ route('companies.index') }}">
                            <thead>
                                <tr role="row">
                                    <th style="width: 50px;">Id</th>
                                    <th>Descripción</th>
                                    <th>R.U.C.</th>
                                    <th style="width: 30px;">Acciones</th>
                                </tr>
                            </thead>
                            {{-- <tbody>
                                @foreach ($companies as $key => $company)
                                    <tr role="row" class="odd">
                                        <td class="sorting_1">{{ $company->id }}</td>
                                        <td><a
                                                href="{{ route('companies.show', $company->id) }}">{{ $company->description }}</a>
                                        </td>
                                        <td>{{ $company->ruc ?? '-' }}</td>

                                        <td style="text-align:center;">
                                            <a href="{{ route('companies.edit', $company->id) }}"
                                                class="rgba-white-sligh"><i class="fa fa-pencil-square-o"
                                                    aria-hidden="true"></i></a>
                                            @can('canDelete', $company)
                                                <a class="btn waves-effect" data-toggle="modal"
                                                    data-target="#eliminacion-registro-{{ $company->id }}"
                                                    href="javascript:;"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                                                @include('components.deleteModal', [
                                                    'url_delete' => route('companies.destroy', $company->id),
                                                    'object' => 'Empresa',
                                                    'id' => $company->id,
                                                    'description' => $company->description,
                                                ])
                                            @endcan
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody> --}}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop


@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script type="module" src="{{ asset('js/admin/companies.js') }}"></script>

    {{-- <script>
        $(function() {
            $("#example1").DataTable({
                "language": {
                    "lengthMenu": "Mostrar _MENU_ registros por página",
                    "zeroRecords": "No se encontró registros",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "No hay registros disponibles",
                    "infoFiltered": "(filtrado de _MAX_ registros)",
                    "search": "Buscar",
                    "searchPlaceholder": "Ingrese texto",
                    "paginate": {
                        "first": "Primero",
                        "previous": "Anterior",
                        "next": "Siguiente",
                        "last": "Último",
                    }
                },
                "order": []
            });
            $('#example1').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
            });
        });
    </script> --}}
@stop

resources/views/admin/companies/show.blade.php
@extends('adminlte::page')

@section('title', 'Empresa')

@section('plugins.Datatables',true)

@section('content_header')
    @include('components.alerts',['object' => 'Empresa'])
    <div class="card-header">
        <a href="{{ route('companies.index') }}" class="btn btn-primary"><i class="fas fa-chevron-left"></i> Empresas</a>
        <a href="{{ route('companies.edit',$company->id) }}" class="btn btn-primary"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Editar</a>
    </div>
@stop

@section('content')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title"><strong>{{ $company->description }}</strong></h3>
        </div>
        <div class="card-body p-0">
            @php $i = 0 @endphp
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th style="width: 10px">#</th>
                        <th>Atributos</th>
                        <th>Valores</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ ++$i }}.</td>
                        <td>Abreviación</td>
                        <td>{{ $company->abbreviation ?? '-' }}</td>
                    </tr>
                    <tr>
                        <td>{{ ++$i }}.</td>
                        <td>Ruc</td>
                        <td>{{ $company->ruc ?? '-' }}</td>
                    </tr>
                    <tr>
                        <td>{{ ++$i }}.</td>
                        <td>Dirección</td>
                        <td>{{ $company->address ?? '-' }}</td>
                    </tr>
                    <tr>
                        <td>{{ ++$i }}.</td>
                        <td>Teléfono</td>
                        <td>{{ $company->telephone ?? '-' }}</td>
                    </tr>
                    <tr>
                        <td>{{ ++$i }}.</td>
                        <td>Nombre de Referencia</td>
                        <td>{{ $company->name_ref ?? '-' }}</td>
                    </tr>
                    <tr>
                        <td>{{ ++$i }}.</td>
                        <td>Teléfono de Referencia</td>
                        <td>{{ $company->telephone_ref ?? '-' }}</td>
                    </tr>
                    <tr>
                        <td>{{ ++$i }}.</td>
                        <td>Correo de Referencia</td>
                        <td>{{ $company->email_ref ?? '-' }}</td>
                    </tr>
                    <tr>
                        <td>{{ ++$i }}.</td>
                        <td>Activo</td>
                        <td>{{ $company->active == 'S' ? 'Si' : 'No' }}</td>
                    </tr>
                    <tr>
                        <td>{{ ++$i }}.</td>
                        <td>Fecha de creación</td>
                        <td>{{ $company->created_at ?? '-' }}</td>
                    </tr>
                    <tr>
                        <td>{{ ++$i }}.</td>
                        <td>Fecha de actualización</td>
                        <td>{{ $company->updated_at ?? '-' }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
@stop